export const GAME = {
  title: "Stonefall Frontier",
  seed: 240613,
  chunkSize: 16,
  worldHeight: 72,
  renderDistance: 4,
  unloadDistance: 6,
  waterLevel: 20,
  dayLengthSeconds: 1200,
  playerHeight: 1.78,
  playerRadius: 0.33,
  walkSpeed: 4.1,
  sprintSpeed: 6.4,
  sneakSpeed: 2.0,
  jumpVelocity: 6.8,
  gravity: 19.5,
  maxHealth: 10,
  maxHunger: 10,
};

export const BLOCKS = {
  0: { id: 0, name: "Air", solid: false, transparent: true, texture: [0,0,0,0,0,0] },
  1: { id: 1, name: "Grass", solid: true, transparent: false, texture: [1,1,0,2,1,1] },
  2: { id: 2, name: "Dirt", solid: true, transparent: false, texture: [2,2,2,2,2,2] },
  3: { id: 3, name: "Stone", solid: true, transparent: false, texture: [3,3,3,3,3,3] },
  4: { id: 4, name: "Log", solid: true, transparent: false, texture: [5,5,4,4,4,4] },
  5: { id: 5, name: "Leaves", solid: true, transparent: true, texture: [6,6,6,6,6,6], alpha: 0.18 },
  6: { id: 6, name: "Sand", solid: true, transparent: false, texture: [7,7,7,7,7,7] },
  7: { id: 7, name: "Water", solid: false, transparent: true, texture: [8,8,8,8,8,8], alpha: 0.52 },
  8: { id: 8, name: "Snow", solid: true, transparent: false, texture: [9,9,9,9,9,9] },
  9: { id: 9, name: "Coal Ore", solid: true, transparent: false, texture: [10,10,10,10,10,10] },
  10: { id: 10, name: "Iron Ore", solid: true, transparent: false, texture: [11,11,11,11,11,11] },
  11: { id: 11, name: "Ruby Ore", solid: true, transparent: false, texture: [12,12,12,12,12,12] },
  12: { id: 12, name: "Titanium Ore", solid: true, transparent: false, texture: [13,13,13,13,13,13] },
  13: { id: 13, name: "Bark", solid: true, transparent: false, texture: [14,14,14,14,14,14] },
  14: { id: 14, name: "Crystal", solid: true, transparent: true, texture: [15,15,15,15,15,15], alpha: 0.42 },
};

export const BLOCK_IDS = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  LOG: 4,
  LEAVES: 5,
  SAND: 6,
  WATER: 7,
  SNOW: 8,
  COAL: 9,
  IRON: 10,
  RUBY: 11,
  TITANIUM: 12,
  BARK: 13,
  CRYSTAL: 14,
};

export const INVENTORY_ITEMS = [
  { id: 1, name: "Grass Block", kind: "block" },
  { id: 2, name: "Dirt Block", kind: "block" },
  { id: 3, name: "Stone Block", kind: "block" },
  { id: 4, name: "Log", kind: "block" },
  { id: 5, name: "Leaves", kind: "block" },
  { id: 6, name: "Sand", kind: "block" },
  { id: 7, name: "Water", kind: "block" },
  { id: 8, name: "Snow", kind: "block" },
  { id: 9, name: "Coal Ore", kind: "block" },
  { id: 10, name: "Iron Ore", kind: "block" },
  { id: 11, name: "Ruby Ore", kind: "block" },
  { id: 12, name: "Titanium Ore", kind: "block" },
];
